config/routes.rb
Rails.application.routes.draw do
  resources :masks
  resources :numbers

  get '/phone_masking', to: 'numbers#index'
  post '/numbers/mask_number'
  post '/masks/transfer'
  

end

app/models/mask.rb
class Mask < ActiveRecord::Base
    belongs_to :number


    before_destroy do
    
        puts 'deleting mask: ' + phone_number

        user = ENV['TROPO_USERNAME']
        pass = ENV['TROPO_PASSWORD']
        app_id = ENV['TROPO_MASKING_APP_ID'] 

        uri = URI.parse("https://api.tropo.com/v1/applications/#{app_id}/addresses/number/#{phone_number}")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = (uri.scheme == "https")

        request = Net::HTTP::Delete.new(uri.request_uri)
        request.basic_auth(user, pass)

        response = http.request(request)
        if response.code != '200'
            if response.code == '404'
                puts 'Warning: mask ' + phone_number + ' was not found in Tropo'
            else
                raise 'Unable to delete mask ' + phone_number + ' from tropo: ' + response.message
            end
        end
    end

end

app/controllers/masks_controller.rb
class MasksController < ApplicationController
  before_action :set_mask, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token


   def transfer 
    puts 'transferring...'

    from = params[:session][:from][:id]
    to = params[:session][:to][:id]

    puts 'from: ' + from
    puts 'to: ' + to 

    mask = Mask.find_by phone_number: Phonelib.parse(to).e164
    number = mask.number.phone_number

    t = Tropo::Generator.new  
    t.transfer(:to => number, :from => from)

    render :json => (t.response)
  end



  # GET /masks
  # GET /masks.json
  def index
    @masks = Mask.all
  end

  # GET /masks/1
  # GET /masks/1.json
  def show
  end

  # GET /masks/new
  def new
    @mask = Mask.new
  end

  # GET /masks/1/edit
  def edit
  end

  # POST /masks
  # POST /masks.json
  def create
    @mask = Mask.new(mask_params)

    respond_to do |format|
      if @mask.save
        format.html { redirect_to @mask, notice: 'Mask was successfully created.' }
        format.json { render :show, status: :created, location: @mask }
      else
        format.html { render :new }
        format.json { render json: @mask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masks/1
  # PATCH/PUT /masks/1.json
  def update
    respond_to do |format|
      if @mask.update(mask_params)
        format.html { redirect_to @mask, notice: 'Mask was successfully updated.' }
        format.json { render :show, status: :ok, location: @mask }
      else
        format.html { render :edit }
        format.json { render json: @mask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masks/1
  # DELETE /masks/1.json
  def destroy
    @mask.destroy
    respond_to do |format|
      format.html { redirect_to masks_url, notice: 'Mask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mask
      @mask = Mask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mask_params
      params.require(:mask).permit(:phone_number, :number_id)
    end
end

app/helpers/masks_helper.rb
module MasksHelper
end

app/views/masks/_form.html.erb
<%= form_for(@mask) do |f| %>
  <% if @mask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mask.errors.count, "error") %> prohibited this mask from being saved:</h2>

      <ul>
      <% @mask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :number_id %><br>
    <%= f.text_field :number_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/masks/edit.html.erb
<h1>Editing Mask</h1>

<%= render 'form' %>

<%= link_to 'Show', @mask %> |
<%= link_to 'Back', masks_path %>

app/views/masks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Masks</h1>

<table>
  <thead>
    <tr>
      <th>Mask</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masks.each do |mask| %>
      <tr>
        <td><%= mask.phone_number %></td>
        <td><%= mask.number.phone_number %></td>
        <td><%= link_to 'Show', mask %></td>
        <td><%= link_to 'Edit', edit_mask_path(mask) %></td>
        <td><%= link_to 'Destroy', mask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mask', new_mask_path %>

app/views/masks/new.html.erb
<h1>New Mask</h1>

<%= render 'form' %>

<%= link_to 'Back', masks_path %>

app/views/masks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Phone number:</strong>
  <%= @mask.phone_number %>
</p>

<p>
  <strong>Number:</strong>
  <%= @mask.number %>
</p>

<%= link_to 'Edit', edit_mask_path(@mask) %> |
<%= link_to 'Back', masks_path %>