config/routes.rb
Rails.application.routes.draw do
  resources :masks
  resources :numbers

  get '/phone_masking', to: 'numbers#index'
  post '/numbers/mask_number'
  post '/masks/transfer'
  

end

app/models/number.rb
class Number < ActiveRecord::Base
    has_many :masks, dependent: :destroy 
    validates :phone_number, phone: true
    validates :phone_number, format: { with: /\+.*/, message: "Must be in international format" }


    @@user = ENV['TROPO_USERNAME']
    @@pass = ENV['TROPO_PASSWORD']
    @@mask_app_id = ENV['TROPO_MASKING_APP_ID']


    def generate_mask
        puts 'generating mask for ' + phone_number

        uri = URI.parse("https://api.tropo.com/v1/applications/#{@@mask_app_id}/addresses")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = (uri.scheme == "https")

        request = Net::HTTP::Post.new(uri.request_uri)
        request.basic_auth(@@user, @@pass)
        request.set_form_data({type: 'number', prefix: get_area_code()})

        response = http.request(request)

        if response.code === '200'
            response_uri = JSON.parse(response.body)['href']
            return extract_number_from_uri(response_uri)
        else
          puts 'generating mask with prefix ' + get_area_code() + ' failed with http ' + response.code + ' and message: ' + response.body
          return generate_random_mask

        end
    end

    
    def generate_random_mask
        puts 'generating random mask for ' + phone_number

        uri = URI.parse("https://api.tropo.com/v1/applications/#{@@mask_app_id}/addresses")

        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = (uri.scheme == "https")

        request = Net::HTTP::Post.new(uri.request_uri)
        request.basic_auth(@@user, @@pass)

        request.set_form_data({type: 'number', prefix: '1'})
        response = http.request(request)
        if response.code === '200'
            response_uri = JSON.parse(response.body)['href']
            return extract_number_from_uri(response_uri)
        else
            puts 'generating mask without prefix failed with http ' + response.code + 'and message: ' + response.body

            return nil
        end
    end


    def get_area_code
        return phone_number[1...5]
    end


    def extract_number_from_uri(uri)
        index_of_plus = uri.index('+')
        return uri[index_of_plus..-1]
    end
end

app/controllers/numbers_controller.rb
class NumbersController < ApplicationController
  before_action :set_number, only: [:show, :edit, :update, :destroy]


  def mask_number
    respond_to do |format|

      provided_number = params[:number]

      puts "number " + provided_number

      if Phonelib.invalid? provided_number
        puts "invalid number"
          format.json {render json: {message: "phone number is invalid"}, status: 500 }
      else
        provided_number = Phonelib.parse(provided_number).e164

        if Number.exists?(:phone_number => provided_number)
          puts "number exists"
          number = Number.find_by phone_number: provided_number
        else
          number = Number.create(phone_number: provided_number);
          if !number.valid?
            puts number.errors.to_json
          end 
        end

        generated_mask = Phonelib.parse(number.generate_mask()).e164
      
        if generated_mask.nil?
          format.json {render json: {message: "unable to generate mask"}, status: 500 }
        else
          mask = Mask.create(phone_number: generated_mask, number: number)
          if !mask.valid?
            puts mask.errors.to_json
          end 
          format.json {render json: {message: generated_mask}}
        end
      end

    end
  end

  

  # GET /numbers
  # GET /numbers.json
  def index
    @numbers = Number.all
  end

  # GET /numbers/1
  # GET /numbers/1.json
  def show
  end

  # GET /numbers/new
  def new
    @number = Number.new
  end

  # GET /numbers/1/edit
  def edit
  end

  # POST /numbers
  # POST /numbers.json
  def create
    @number = Number.new(number_params)

    respond_to do |format|
      if @number.save
        format.html { redirect_to @number, notice: 'Number was successfully created.' }
        format.json { render :show, status: :created, location: @number }
      else
        format.html { render :new }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /numbers/1
  # PATCH/PUT /numbers/1.json
  def update
    respond_to do |format|
      if @number.update(number_params)
        format.html { redirect_to @number, notice: 'Number was successfully updated.' }
        format.json { render :show, status: :ok, location: @number }
      else
        format.html { render :edit }
        format.json { render json: @number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /numbers/1
  # DELETE /numbers/1.json
  def destroy
    @number.destroy
    respond_to do |format|
      format.html { redirect_to numbers_url, notice: 'Number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_number
      @number = Number.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def number_params
      params.require(:number).permit(:phone_number)
    end
end

app/helpers/numbers_helper.rb
module NumbersHelper
end

app/views/numbers/_form.html.erb
<%= form_for(@number) do |f| %>
  <% if @number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@number.errors.count, "error") %> prohibited this number from being saved:</h2>

      <ul>
      <% @number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/numbers/edit.html.erb
<h1>Editing Number</h1>

<%= render 'form' %>

<%= link_to 'Show', @number %> |
<%= link_to 'Back', numbers_path %>

app/views/numbers/index.html.erb
<h1>Phone Masking</h1>


<%= form_tag("/numbers/mask_number", method: "post", remote: true, id: "mask_number_form") do %>
  <%= label_tag(:number, "Please enter a number to mask:") %>
  <%= text_field_tag(:number) %>
  <%= submit_tag("Generate Mask") %>
  &nbsp;
  &nbsp;
<% end %>




<h1>Listing Numbers</h1>

<table id="numbers_table" data-behavior="display-masks-table">
  <thead id = "numbers_head">
    <tr>
      <th>Number</th>
      <th>Masks</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody id="numbers_body">
  </tbody>
</table>

app/views/numbers/new.html.erb
<h1>New Number</h1>

<%= render 'form' %>

<%= link_to 'Back', numbers_path %>

app/views/numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @number.number %>
  <br>
  <strong>Masks:</strong>
  <ul>
  <% @number.masks.each do |mask| %>
    <li><%= mask.mask %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Back', numbers_path %>